name: This is the first GitHub Actions Demo
run-name: ${{ github.actor }} has triggered the pipeline

on: 
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-infra:
    name: terraform-ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Initialize
        id: init
        run: terraform init
        working-directory: ./terraform
      - name: Terraform Validation
        id: validate
        run: terraform validate
        working-directory: ./terraform
      - name: Terraform Planning
        id: plan
        run: terraform plan
        working-directory: ./terraform
      - name: Terraform Destroying
        id: destroy
        run: terraform destroy --auto-approve   
        working-directory: ./terraform